# Generated by Django 5.0.6 on 2025-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(default='home', max_length=10),
            preserve_default=False,
        ),
    ]
