# Generated by Django 5.0.6 on 2025-06-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist_delete_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
